#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opencl-headers
Version  : 2021.04.29
Release  : 6
URL      : file:///aot/build/clearlinux/packages/opencl-headers/opencl-headers-v2021.04.29.tar.gz
Source0  : file:///aot/build/clearlinux/packages/opencl-headers/opencl-headers-v2021.04.29.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: opencl-headers-data = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# OpenCL<sup>TM</sup> API Headers
This repository contains C language headers for the OpenCL API.

%package data
Summary: data components for the opencl-headers package.
Group: Data

%description data
data components for the opencl-headers package.


%package dev
Summary: dev components for the opencl-headers package.
Group: Development
Requires: opencl-headers-data = %{version}-%{release}
Provides: opencl-headers-devel = %{version}-%{release}
Requires: opencl-headers = %{version}-%{release}

%description dev
dev components for the opencl-headers package.


%prep
%setup -q -n opencl-headers
cd %{_builddir}/opencl-headers

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622373912
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
%cmake ..
make  %{?_smp_mflags}  V=1 VERBOSE=1  V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1622373912
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
## install_append content
#mkdir -p %{buildroot}/usr/include/CL
#install -m644 CL/* %{buildroot}/usr/include/CL
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/CL/cl.h
/usr/include/CL/cl_d3d10.h
/usr/include/CL/cl_d3d11.h
/usr/include/CL/cl_dx9_media_sharing.h
/usr/include/CL/cl_dx9_media_sharing_intel.h
/usr/include/CL/cl_egl.h
/usr/include/CL/cl_ext.h
/usr/include/CL/cl_ext_intel.h
/usr/include/CL/cl_gl.h
/usr/include/CL/cl_gl_ext.h
/usr/include/CL/cl_half.h
/usr/include/CL/cl_icd.h
/usr/include/CL/cl_layer.h
/usr/include/CL/cl_platform.h
/usr/include/CL/cl_va_api_media_sharing_intel.h
/usr/include/CL/cl_version.h
/usr/include/CL/opencl.h
